Class {
	#name : 'TITCollectionElementTypesFoundMarker',
	#superclass : 'TITStructureNodeTypeCollector',
	#category : 'TypeInfoTools-Core-Inference',
	#package : 'TypeInfoTools-Core',
	#tag : 'Inference'
}

{ #category : 'accessing' }
TITCollectionElementTypesFoundMarker >> sourceName [

	^ 'Element types found'
]

{ #category : 'accessing' }
TITCollectionElementTypesFoundMarker >> weight [

	^ 1.5
]
